### ISSUE TITLE
Attack ray of a queen, that was obtained via promoting

### ISSUE THREAD

**Issue by egormoroz** [MicAPic/mlChess#1]
## Description
The king is able to walk into the attack ray of the queen that was obtained by promoting (pic attached)
![image](https://user-images.githubusercontent.com/71780262/165925093-0be7c0ca-c31f-40f3-b33c-00c0c4de3026.png)

## Steps to reproduce
Start a new game, perform the following moves:
1. e4 f5 2. exf5 Kf7 3. f6 Ke6 4. f7 Kf6 5. fxg8=Q

**Comment by MicAPic** [comment]
Fixed in a05a84e4d73ededa6336b253070eee3ca35d9a7b:

![image](https://user-images.githubusercontent.com/73939030/165929040-cd3f631c-4131-4123-8f8e-eaa8c04b9f47.png)
